# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui printsupport

TEMPLATE = app
TARGET = CameraCalibrator
DESTDIR = ./Bin
CONFIG += debug
DEFINES += RVISIONLIB_HAVE_QT
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(CameraCalibrator.pri)
win32:RC_FILE = CameraCalibrator.rc
